### ISSUE TITLE
Feature Request: Configurable Option to Enable Burn Countdown

### ISSUE THREAD

**Issue by RushHour2k5** [KSPSnark/BetterBurnTime#12]
I understand that the Burn Countdown was marked obsolete with KSP 1.5 however I do not know why. Can you please provide a configurable option in the CFG file to either have it disabled by default or enable it?

**Comment by KSPSnark** [comment]
It's marked obsolete because it's no longer necessary (since the stock game now includes a countdown.)

**Comment by RushHour2k5** [comment]
@KSPSnark, maybe I'm missing something but I'm on the latest version of KSP with the Making History DLC and do not have a countdown for optimal burn. I have the Estimated Burn and Node in T- counters but not the optimal burn to tell me when to start so it's half before Node and half after Node. I'm requesting the ability to have the "pips" enabled as they're so called in the config file.

**Comment by KSPSnark** [comment]
Yes, you're missing something. ;)
![countdown](https://i.imgur.com/NO4HYHM.png)
^ That right there.  It's a stock feature, has been there since KSP 1.5.  Just make sure that "Extended Burn Indicator" is turned on in your game settings.

And yes, I understand perfectly well what you're requesting, and I'm saying that the answer is "no" because it's not needed, due to the stock feature shown above.

**Comment by RushHour2k5** [comment]
@KSPSnark, thank you! New player to KSP so I did not know a setting needed to be activated and most of the searches I ran kept pulling information from 2014 or prior. Would prefer the pips but this works. Thanks again!
