### ISSUE TITLE
Use SetParent for changing transform parent

### ISSUE THREAD

**Issue by DMagic1** [KSPSnark/BetterBurnTime#3]
Better Burn Time generates this error several times every time it is initialized:

         Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.

I think it's coming from here (since this method is dealing with UI elements it converts the standard transform to a RectTransform): https://github.com/KSPSnark/BetterBurnTime/blob/master/src/BurnInfo.cs#L262

This is harmless as far as I know, but somewhat irritating to see when you are monitoring the log a lot. The solution is to use:

       clonedObject.transform.SetParent(source.gameObject.transform.parent, false);

**Comment by KSPSnark** [comment]
Thanks for the catch (and the solution)!

I've released v1.5.2, which fixes the issue.

**Comment by KSPSnark** [comment]
Addendum:  Nope, can't do it, sorry.  I've had to release 1.5.3 to undo the proposed "fix".

The problem is that calling SetParent rather than "parent =", as you suggest, totally breaks the navball, including pieces of it that BetterBurnTime doesn't even do anything with.  Alas.

So, will just have to live with that error, unless anyone knows how to get rid of it without breaking the navball (I don't have the bandwidth to investigate this myself).

**Comment by Jaidan** [comment]
So I'm admittedly way out of my element because my expertise is in web services development...but this documentation: https://docs.unity3d.com/ScriptReference/Transform.SetParent.html indicates to me that you actually could/should use:

`clonedObject.transform.SetParent(source.gameObject.transform.parent);`

"This method is the same as the parent property except that it is possible to make the Transform keep its local orientation rather than its global orientation. This is managed by setting the worldPositionStays parameter to false. When SetParent is called with only the single Transform argument the worldPositionStays argument is set to true."

Reason being: you are currently setting the attribute which has the same behavior as calling `SetParent` with `true` (or omitting the argument)

**Comment by KSPSnark** [comment]
So.  Your suggestion, i.e. calling "setParent(...)" rather than ".parent = ...", is exactly DMagic was just suggesting when he opened this issue.  I made precisely that change and released it as 1.5.2.  This broke the navball horribly, to the point of being almost unplayable.  So now I've changed it back to the way it was.

Which, of course, means that the issue that DMagic raised in the first place is back again, too.  I'd love to fix it, but not unless I have a fix that doesn't break something else.  I don't currently know of any such fix myself, and unfortunately I don't have the bandwidth to go out and find such a fix.  So at this point, it's going to have to stay that way, until/unless someone can come up with an actual, working solution and feed it to me with a spoon.  ;-)

**Comment by DMagic1** [comment]
There are two SetParent overrides, with and without the bool related to its position and orientation. The error method says to use the second method with the bool set to false, but maybe that's wrong. Using the first override is equivalent to setting the bool to true.

That said, there are some really weird things that can happen with the Unity UI, things that make no logical sense looking at it from the outside, so maybe it's best to leave it as it is.
