### ISSUE TITLE
Nav ball overlay issues 1.5.2

### ISSUE THREAD

**Issue by Jaidan** [KSPSnark/BetterBurnTime#4]
Upgraded to 1.5.2.  Had issues with the navball overlay during target approach mode and impact timing modes.  I reverted to 1.5.1 and the issue went away.  I restarted once with 1.5.2.  I've attached a screenshot of what I saw during the target approach mode.  Sorry I didn't get the landing effect, but it was nearly identical.  Maneuver node guidance appeared to be unaffected and the effects only occurred while in the applicable ranges for approach to target and impact.

Noted issues:
The top of the navball is overlayed over the velocity indicators.
The attitude indication clips the prograde/target reticule and obscures it.
The time to target/estimated burn time indications are missing.
![screenshot33](https://cloud.githubusercontent.com/assets/109307/21149498/80003108-c110-11e6-8e55-ee6eaa0a59c0.png)

**Comment by KSPSnark** [comment]
There's something very weird going on there.  In particular, the fact that the center portion of the navball is overlaid on the velocity indicator is seriously bizarre.  I don't see how BetterBurnTime could possibly be affecting that-- it doesn't touch or modify that part of the navball in any way, it just tinkers with some text boxes on the periphery.

Certainly I can't reproduce this issue myself-- everything works just fine for me, I can't make that happen.

It appears that you're running a bunch of mods.  If reverting from 1.5.2 to 1.5.1 "fixes" the problem, then my guess is that there's some interaction between BetterBurnTime and one of your mods that's causing the issue.  It's not something I can debug, since I don't know what all the mods you're running are.

Can you narrow it down to which of the other mods is the issue?  i.e., first, verify that you do *not* get this issue if you uninstall everything else and run with just BBT, then try adding the mods in and see which one of them is not playing nice with BBT.

Without knowing that, there's basically nothing I can do.

**Comment by Mitalie** [comment]
I get this without any other mods active. Even did a "verify local files" from Steam and started a new save. With two stock craft close to each other, whenever I fly one and target the other, navball breaks.
[Save attached](https://github.com/KSPSnark/BetterBurnTime/files/650745/navball-bug-repro.zip)

**Comment by KSPSnark** [comment]
OK, thanks, will investigate.

**Comment by KSPSnark** [comment]
Yep, 1.5.2 is broken, all right.  The "fix" to [this issue](https://github.com/KSPSnark/BetterBurnTime/issues/3) is what caused it.

I've released 1.5.3 to undo the "fix" and put it back the way it was.
